### ISSUE TITLE
Korrekte Zeilenumbrüche in `\code{}` Blöcken

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/NoWayOut-Docs#2]
Korrekte Zeilenumbrüche in `\code{}` Blöcken

**Comment by wfailla** [comment]
@fin-ger Dazu habe ich auf die schnelle nichts gefunden, wir sollten heute Abend da nochmal gucken wie wir das dann am besten machen.

**Comment by fin-ger** [comment]
@wfailla Der erste Google Treffer gab mir das hier:

http://tex.stackexchange.com/questions/10377/texttt-overfull-hbox-problem

Könnte das der Lösung näher kommen?
